In [11]:
import pandas as pd
from datasets import load_dataset

In [ ]:
ds = load_dataset("lang-uk/recruitment-dataset-job-descriptions-english")

ds["train"].to_csv("dataset/dataset_01.1/datajobs.csv")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Creating CSV from Arrow format: 100%|██████████| 142/142 [00:04<00:00, 28.85ba/s]

277496957

In [3]:
df = pd.read_csv("dataset/dataset_01.1/jobs.csv")
len(df)

141897

In [4]:
df.head(1)

,Position,Long Description,Company Name,Exp Years,Primary Keyword,English Level,Published,Long Description_lang,id,__index_level_0__
0,10 + Blockchain Nodes / Masternodes to set up,*Requirements*\r\n\r\nWe're looking for a long...,MyCointainer,2y,Sysadmin,intermediate,2020-10-01T00:00:00+03:00,en,c0ca96e7-85df-50df-a64e-d934cd02a170,27461

In [ ]:
# 1. Select the columns correctly using a list
selected_columns = df[['Position', 'Long Description']]

# 2. Save to a new CSV file
selected_columns.to_csv('dataset/dataset_01.1/Job_Posting_Subset.csv', index=False)

print("File saved successfully!")

File saved successfully!

In [6]:
df_new = pd.read_csv('dataset/dataset_01.1/Job_Posting_Subset.csv')
df_new.head()

,Position,Long Description
0,10 + Blockchain Nodes / Masternodes to set up,*Requirements*\r\n\r\nWe're looking for a long...
1,10 .NET Developers (Middle and Senior level),"Greetings! My name is Maria, I am in urgent ne..."
2,"10X Engineer (co-founder, #4 employee, USD 11-...",**Product**\r\nThe product is a live video cha...
3,16 - Amazon Brand Manager,"Currently, TCM expanding its activities to Ukr..."
4,16 - Amazon Brand Manager,"Hello,\r\nWe, MIMIRB2B, are an outstaff compan..."

In [7]:
len(df_new)

141897

In [ ]:
df_new.columns = ['title', 'description']
df_new.to_csv('dataset/dataset_01.1/dataset01.1.csv', index=False)

print("Final dataset saved with new column names!")

Final dataset saved with new column names!

In [10]:
df = pd.read_csv("dataset/dataset_01.1/dataset01.1.csv")
df

,title,description
0,10 + Blockchain Nodes / Masternodes to set up,*Requirements*\r\n\r\nWe're looking for a long...
1,10 .NET Developers (Middle and Senior level),"Greetings! My name is Maria, I am in urgent ne..."
2,"10X Engineer (co-founder, #4 employee, USD 11-...",**Product**\r\nThe product is a live video cha...
3,16 - Amazon Brand Manager,"Currently, TCM expanding its activities to Ukr..."
4,16 - Amazon Brand Manager,"Hello,\r\nWe, MIMIRB2B, are an outstaff compan..."
...,...,...
141892,Таргетолог,We are looking for a highly motivated and resu...
141893,Таргетолог,We are looking for an experienced targetologis...
141894,Теаm Lead React,Responsibilities\r\n • Analyze and estimate...
141895,Тестувальник,Duties and Responsibilities\r\n● HelpdDeliver ...
141896,Хмарний архітектор DevOps / DevOps Cloud Archi...,We are looking for a talented and brilliant D...